;ALP for generating 1 Second Delay 

	MOV TMOD,#01H	;SELECT TIMER 0, MODE 1
	MOV R0,#15		;LOAD R0 WITH 15
BACK:MOV TL0,#0FDH	;LOAD TLO WITH FDH
	MOV TH0,#0FH	;LOAD THO WITH 0FH
	SETB TR0		;START TIMER
HERE:JNB TF0,HERE	;CHECK FOR OVERFLOW
	CLR TF0			;CLEAR TF0
	DJNZ R0,BACK	
	CLR TR0			;STOP TIMER
	END