; Finding Largest Elemet in an array (Block of data)

MOV R2,#04H ;       	 	INITIALIZING PASS COUNTER
BEGIN:MOV R3,02H ;	 		INITIALIZING ITERATION COUNTER
	  MOV R0,#40H; 	  		INITIALIZING LOCATION COUNTER
	 BACK:MOV A,@R0; 		MOVE CONTENT OF LOCATION POINTED BY R0 TO A
		  INC R0;    		INCREMENT R0
		  MOV B,@R0; 		MOVE CONTENT OF LOCATION POINTED BY R0 TO B
		  CJNE A,B,L1;		COMPARE A AND B AND JUMP TO L1 IF NOT ZERO
		  SJMP L2; 			SHORT JUMP TO L2
		  L1:JNC L2; 		JUMP TO L2 IF CARRY EQUAL TO 1
			MOV @R0,A;  	MOVE A TO LOCATION POINTED BY R0
			DEC R0; 		DECREMENT R0
			MOV @R0,B;  	MOVE B TO LOCATION POINTED BY R0
			INC R0; 		INCREMENT R0
		  L2:DJNZ R3,BACK; 	DECREMENT R3 AND JUMP TO BACK IF NOT ZERO
SJMP $;
END	