;Add 2 16 bit number using Indirect addressing mode

	MOV R0,#30H	;MOVE ADDRESS OF 1ST OPERAND TO	R0
	MOV R1,#32H	;MOVE ADDRESS OF 2ND OPERAND TO R1
	MOV A,@R0	;MOVE DATA PIONTED BY R0 TO A
	ADD A,@R1	;ADD A AND DATA POINTED BY R1
	MOV 40H,A	;MOVE ACCUMULATOR CONTENT TO 40H ADDRESS LOCATION
	INC R0		;INCREMENT R0
	INC R1		;INCREMENT R1
	MOV A,@R0	;MOVE DATA POINTED BY R0 TO A
	ADDC A,@R1	;ADD A AND DATA POINTED BY R1 WITH CARRY
	MOV 41H,A	;MOVE ACCUMULATOR CONTENT TO 41H ADDRESS LOCATION
	JNC L1		;JUMP TO L1 IF CARRY=0
	SETB 10H	;SET BIT 10H WHICH IS IN BIT ADDRESSABLE RAM 
	MOV 42H,22H ;MOV 22H BYTE TO 42H ADDRESS 
	SJMP L2		;JUMP TO L2
L1: MOV 42H,#00H	;MOV 00H BYTE TO 42H ADDRESS
L2: SJMP $
	END