;To find cube of 8-bit number

MOV A,#0FFH	;A=FFH
MOV B,#0FFH	;B=FFH
MUL AB		;MULTIPLY A AND B,A=01H,B=FEH
MOV R0,B	;R0=FEH
MOV B,#0FFH	;B=FFH
MUL AB		;MULTIPLY A AND B,A=FFH,B=00H
MOV R1,B	;R1=00H
MOV R2,A	;R2=FFH
MOV A,R0	;A=FEH
MOV B,#0FFH	;B=FFH
MUL AB		;MULTIPLY A AND B,A=02H,B=FDH
ADD A,R1	;A=00H+02H=02H
MOV R3,A	;MOVE CONTENT OF A TO R3,R3=02H
MOV A,B		;A=FDH
ADDC A,#00H	;A=A+00H+CY=FDH
MOV R4,A	;R4=FDH
SJMP $
END