; To find square of an 8-bit number
    
	
	MOV A,30H	;CONTENT OF 30H LOCATION IS MOVED TO A
	MOV B,30H	;CONTENT OF 30H LOCATION IS MOVED TO B
	MUL AB		;MULTIPLY A AND B ,A IS STORED WITH LOWER BYTE AND B WITH HIGHER BYTE OF RESULT
	MOV 50H,B	;B CONTENT IS MOVED TO 50H ADDRESS LOCATION
	MOV 51H,A	;A CONTENT IS MOVED TO 51H ADDRESS LOCATION
	SJMP $		
	END