;ALP for an 8-bit Counter


	 MOV A,#99H	    ;LOAD A WITH 99H
BACK:ACALL DELAY	;CALL DELAY SUBROUTINE
	 ADD A,#99H	 	;ADD A WITH A 99H
	 DA A			;DECIMAL ADJUST A
	 JNZ BACK		;JUMP TO BACK IF A IS NOT ZERO
	 SJMP $			;TERMINATE THE PROGRAM IF A=0
DELAY:
	 MOV R0,#0FFH
L1:  MOV R1,#0FFH
L2:  MOV R2,#0FFH
L3:  DJNZ R2,L3
	 DJNZ R1,L2
	 DJNZ R0,L1
	 RET
	 END
	 