;Count the number of 0s and 1s in binary form of a number


		CLR C		;CLEAR CARRY BIT
		MOV R0,#00H	;CLEAR R0 TO STORE NUMBER OF 1s
		MOV R1,#00H	;CLEAR R1 TO STORE NUMBER OF 0s
		MOV R2,#08H ;INITIALIZE COUNTER WITH 08H
		MOV A,#0FCH	;A=FCH
AGAIN:	RRC A		;ROTATE RIGHT A WITH CARRY
		JC L1		;JUMP TO L1 IF C=1
		INC R0		;INCRREMENT R0(COUNT OF ZERO)
		SJMP SKIP	;JUMP TO SKIP
L1:		INC R1		;INCRREMENT R0(COUNT OF ZERO)
SKIP:   DJNZ R2,AGAIN;DECREMENT R2 AND JUMP TO AGAIN IF R2 IS NOT EQUAL TO 0
		SJMP $
		END