;ALP to check the Given number is Even or Odd
		
		CLR C		;CLEAR CARRY BIT
		MOV A,#0FFH	;A=FFH
		RLC A		;ROTATE LEFT WITH CARRY
		JC L_NEG	;JUMP TO L_NEG IF C=1
		MOV R0,#0FFH;R0=FFH(NUMBER IS POSITIVE)
		SJMP SKIP	
L_NEG:	MOV R1,#0FFH;R1=FFH(NUMBER IS NEGETIVE)
SKIP:	SJMP $
		END