;Code conversion-BCD to ASCII




MOV A,#10010010B	;A=10010010H
MOV B,A				;B=A
ANL A,#0FH			;MASK UPPER NIBBLE OF A
ADD A,#30H			;ADD A WITH 30H
MOV R0,A			;MOVE A CONTENT TO R0
MOV A,B				;MOVE B CONTENT TO A
ANL A,#0F0H			;MASK LOWER NIBBLE OF A  
SWAP A				;SWAP LOWER AND UPPER NIBBLE OF A
ADD A,#30H			;ADD A WITH 30H
MOV R1,A			;MOVE A CONTENT TO R1
SJMP $
END