;Code Conversion- Decimal to ASCII

	MOV R0,#205D		;LOAD DECIMAL VALUE
	//FOR HIGHER NIBBLE
	MOV A,R0		;MOV NUMBER TO A
	ANL A,#0F0H		;MASK LOWER NIBBLE
	SWAP A			;SWAP UPPER AND LOWER NIBBLE
	MOV R1,A		;MOVE SWAPED VAlUE TO R1
	SUBB A,#0AH		;SUBTRACT A WITH 0AH 
	JC LOOP			;JUMP TO LOOP IF C=1
	ADD A,#41H		;ADD WITH 41H
	SJMP DGT1
LOOP:MOV A,R1		;MOVE SWAPPED DATA TO A	
	ADD A,#30H		;ADD WITH 30H
DGT1:MOV R2,A		;MOV RESULT TO R2
	//FOR LOWER NIBBLE
	MOV A,R0		;MOV DECIMAL NUMBER TO A
	ANL A,#0FH		;MASK UPPER BYTE
	MOV R1,A		;MOVE MASKED VALUE TO R1
	SUBB A,#0AH		;SUBTRACT A WITH 0AH
	JC LOOP1
	ADD A,#41H		;ADD A WITH 41H
	SJMP DGT2		
LOOP1:MOV A,R1		;MOVE R1 TO A
	ADD A,#30H		;ADD A WITH 30H
DGT2:MOV R3,A		;MOVE RESULT TO R3
	SJMP $
	END
	
